- name: variables from files
  hosts: localhost
  vars_files:
  - variable.yaml
  tasks:
  - name: check variables
    ansible.builtin.debug:
     msg: "Hi, Learning a {{Course}}, Trainer is {{Trainer}}, duration is {{Duration}}"