- name: vars from inventory
  hosts: local
  tasks:
  - name: check variables
    ansible.builtin.debug:
      msg: "Hai, I am learning {{Course}}, Trainer is {{Trainer}}, duration is {{Duration}}"
      