- name: checking date types
  hosts: localhost
  vars:
    NAME: muniprasd #key value 
    Skills:  #Skill is a list type
    - DevOps
    - shell
    - Docker
    - Kubernetes
    Experience: #Experience is map type. it contains key value pairs
     DevOps: 3
     Aws: 3
     Docker: 3
    Trainer: True # boolean
    tasks:
    - name: print the key value pairs
      ansible.builtin.debug:
        msg: "Hai: {{NAME}}"

    - name: print the list
      ansible.builtin.debug:
        msg: "Skills: {{Skills}}"

    - name: print the map 
      ansible.builtin.debug:
        msg: "Experience: {{Experience}}"

    - name: print the boolean
      ansible.builtin.debug:
        msg: "He is a Trainer:{Trainer}"

    