- name: conditions
  hosts: localhost
  tasks:
  - name: check roboshop user exists or not
    ansible.builtin.command: id roboshop
    register: USER #user is variable name
    ignore_errors: true # ansible will not exit even it got error
  - name: print the variable value
    ansible.builtin.debug:
      msg: "user output is: {{USER}}"
